### ISSUE TITLE
what was the setup of the MPP databases

### ISSUE THREAD

**Issue by jwijffels** [szilard/benchm-databases#4]
Thanks for the benchmark. 
What was the setup for the MPP databases?
Was GreenPlum among these?

**Comment by jaten-saucelabs** [comment]
@szilard Can you say what these MPPs were? I'm particularly curious about MPP-1, which appears to having blazing fast aggregation performance, near 0.5 seconds as opposed to 7 seconds for MonetDB.

**Comment by szilard** [comment]
Unfortunately several MPPs prohibit in their licence agreement publishing benchmarks (disclosing performance measurements to 3rd parties). I know, it's silly, especially from those guys who are in the top.

**Comment by aradev** [comment]
Would it be possible to list the names separately without matching them to the specific benchmark result?
